### ISSUE TITLE
Feature: more view option of image and option to save image

### ISSUE THREAD

**Issue by JakubGolebiowski** [Raf-Mac475/Object_Detection#7]
Please implement:
- saving segmented image 
- zoom in/out - fixed with #8 
- autosize for displayed images - fixed with #8

**Comment by JakubGolebiowski** [comment]
Still, it will be nice to have an option to **saving segmented image** @Raf-Mac475

**Comment by Raf-Mac475** [comment]
Added branch with saving functionality #9

**Comment by JakubGolebiowski** [comment]
Nice, sorry for late response. It will work for me. For future, maybe better to add dedicated button, but it is ok, so I am closing this issue. Thanks! :smile:
